name: research-analytics-suite
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.12
  - pip

  # Core BLAS/LAPACK (macOS: use OpenBLAS, not MKL)
  - openblas
  - libopenblas
  - numpy  # linked against openblas
  - scipy>=1.10.0  # linked against openblas

  # Core dependencies
  - aioconsole
  - aiofiles
  - aiosqlite
  - bleak
  - boto3
  - cachetools
  - dask
  - diskcache
  - fastavro
  - matplotlib
  - nest-asyncio
  - openpyxl
  - pandas
  - paramiko
  - prettytable
  - psutil
  - pyarrow
  - pymongo
  - pynvml
  - pytest
  - pytest-asyncio
  - pytest-cov
  - pyserial
  - scikit-learn
  - statsmodels>=0.13.0
  - pytables

  # PyTorch (ensure macOS builds are from pytorch channel)
  - pytorch::torch
  - pytorch::torchaudio
  - pytorch::torchvision

  # Pip-only deps
  - pip:
      - dearpygui
      - dearpygui-async
      - tensorflow
      - pillow
      - jupyterlab-pygments
      - jupyter-client
      - pure-eval
