name: research-analytics-suite
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.12
  - pip
  - aioconsole
  - aiofiles
  - aiosqlite
  - bleak
  - boto3
  - cachetools
  - dask
  - diskcache
  - fastavro
  - matplotlib
  - nest-asyncio
  - numpy
  - openpyxl
  - pandas
  - paramiko
  - prettytable
  - psutil
  - pyarrow
  - pymongo
  - pynvml
  - pytest
  - pytest-asyncio
  - pytest-cov
  - pyserial
  - scikit-learn
  - scipy>=1.10.0
  - statsmodels>=0.13.0
  - pytables
  - pytorch::torch
  - pytorch::torchaudio
  - pytorch::torchvision
  - pip:
      - dearpygui
      - dearpygui-async
      - tensorflow
