name: research-analytics-suite
channels:
  - anaconda
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - aioconsole
  - aiofiles
  - aiosqlite
  - anaconda-anon-usage
  - anaconda-client
  - anaconda-cloud-auth
  - anaconda-navigator
  - annotated-types
  - anyio
  - asttokens
  - attrs
  - backcall
  - beautifulsoup4
  - bleach
  - bleak
  - boltons
  - bottleneck
  - brotli
  - brotli-bin
  - brotli-python
  - boto3
  - botocore
  - cachey
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - charset-normalizer
  - click
  - cloudpickle
  - colorama
  - conda
  - conda-content-trust
  - conda-package-handling
  - conda-package-streaming
  - conda-repo-cli
  - conda-token
  - console_shortcut
  - contourpy
  - cryptography
  - cycler
  - dask[dataframe]
  - dask-core
  - dask-expr
  - decorator
  - defusedxml
  - dnspython
  - docopt
  - et_xmlfile
  - exceptiongroup
  - executing
  - fastavro
  - fastparquet
  - filelock
  - fonttools
  - freetype
  - fsspec
  - h11
  - h5py
  - hdf5
  - h2
  - hpack
  - httpcore
  - hyperframe
  - icu
  - idna
  - importlib-metadata
  - importlib_resources
  - intel-openmp
  - ipython
  - jaraco.classes
  - jedi
  - jinja2
  - jmespath
  - joblib
  - jpeg
  - jsonpatch
  - jsonpointer
  - jsonschema
  - jsonschema-specifications
  - jupyter_core
  - keras
  - keyring
  - kiwisolver
  - krb5
  - lerc
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libclang
  - libclang13
  - libdeflate
  - libffi
  - liblapack
  - libpng
  - libpq
  - libtiff
  - libwebp-base
  - locket
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - menuinst
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - mpmath
  - more-itertools
  - navigator-updater
  - nbclient
  - nbconvert
  - nbformat
  - networkx
  - nest-asyncio
  - numexpr
  - numpy
  - numpy-base
  - openjpeg
  - openpyxl
  - openssl
  - packaging
  - pandas
  - pandocfilters
  - paramiko
  - parso
  - partd
  - patsy
  - pickleshare
  - pip
  - pipreqs
  - pkce
  - pkgutil-resolve-name
  - platformdirs
  - pluggy
  - ply
  - prettytable
  - prompt-toolkit
  - psutil
  - pyaudio
  - pycosat
  - pycparser
  - pydantic
  - pydantic-core
  - pygments
  - pyjwt
  - pymongo
  - pyopenssl
  - pyparsing
  - pytest
  - pytest-asyncio
  - pytest-cov
  - pyqt
  - pyqt5-sip
  - pyqtwebengine
  - pyserial
  - pyserial-asyncio
  - pysocks
  - pytables
  - python
  - python_abi
  - python-dateutil
  - python-dotenv
  - python-fastjsonschema
  - python-tzdata
  - pytz
  - pynvml
  - pywin32
  - pywin32-ctypes
  - pyyaml
  - pyzmq
  - qt-main
  - qt-webengine
  - qtpy
  - referencing
  - requests
  - requests-toolbelt
  - rich
  - rpds-py
  - ruamel.yaml
  - ruamel.yaml.clib
  - s3transfer
  - scikit-learn
  - scipy
  - semver
  - setuptools
  - sip
  - six
  - snappy
  - sniffio
  - soupsieve
  - statsmodels
  - sqlite
  - sympy
  - tbb
  - threadpoolctl
  - tinycss2
  - tomli
  - toolz
  - torch
  - torchaudio
  - torchvision
  - tornado
  - tqdm
  - traitlets
  - typing_extensions
  - ujson
  - unicodedata2
  - urllib3
  - vc
  - vs2015_runtime
  - wcwidth
  - webencodings
  - wheel
  - win_inet_pton
  - xz
  - yaml
  - yarg
  - zipp
  - zlib
  - zstandard
  - zstd
  - pip:
      - dearpygui
      - dearpygui-async
      - jupyterlab-pygments
      - jupyter-client
      - pillow
      - pure-eval
      - tensorflow
