name: Install Dependencies

on:
  workflow_call:

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --user -r requirements.txt
        pip install --user pytest
        pip install --user pytest-cov
        pip install --user pytest-asyncio

    - name: Add pip user base to PATH
      run: echo "${HOME}/.local/bin" >> $GITHUB_PATH
