name: Install Dependencies

on: [workflow_call]

jobs:
  install:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --user -r requirements.txt
        pip install --user pytest pytest-asyncio
