name: Research Analytics Suite - FULL Test Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: ./.github/workflows/setup-python.yml
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      uses: ./.github/workflows/install-dependencies.yml.yml
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run ALL Tests
      uses: ./.github/workflows/run-tests.yml.yml
      with:
        log-level: DEBUG
