name: Research Analytics Suite - FULL Test Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}

    - name: Create conda environment
      run: conda env create -f environment.yml

    - name: Activate conda environment
      run: echo "conda activate $(head -n 1 environment.yml | cut -d ' ' -f 2)" >> $GITHUB_ENV  # Extracts and activates the environment name from environment.yml

    - name: Install pip dependencies
      run: |
        source activate $(head -n 1 environment.yml | cut -d ' ' -f 2)
        python -m pip install --upgrade pip
      shell: bash -l {0}

    - name: Run ALL Tests
      env:
        PYTHON_LOG_LEVEL: DEBUG  # Set the log level to DEBUG for tests
      run: |
        source activate $(head -n 1 environment.yml | cut -d ' ' -f 2)
        pytest --log-level=DEBUG
      shell: bash -l {0}
