name: Research Analytics Suite - Full Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
        - os: ubuntu-latest
          path: ~/.cache/pip
        - os: macos-latest
          path: ~/Library/Caches/pip
        - os: windows-latest
          path: ~\AppData\Local\pip\Cache

    steps:  
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - uses: actions/cache@v3
      with:
        path: ${{ matrix.path }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
         ${{ runner.os }}-pip-

    - name: Install HDF5 on macOS
      if: runner.os == 'macOS'
      run: |
        brew install hdf5

    - name: Install MKL on macOS
      if: runner.os == 'macOS'
      run: |
        brew install intel-openmp
        pip install mkl-service

    - name: Install dependencies
      run: |
        if [[ "${{ runner.os }}" == 'macOS' ]]; then
          export HDF5_DIR=$(brew --prefix hdf5)
        fi
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        pytest --log-level=DEBUG
