name: Research Analytics Suite - Full Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
        - os: ubuntu-latest
          venv-path: .venv
        - os: macos-latest
          venv-path: .venv
        - os: windows-latest
          venv-path: .venv

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - uses: actions/cache@v3
      id: venv-cache
      with:
        path: ${{ matrix.venv-path }}
        key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-

    - name: Set up virtual environment on Ubuntu
      if: runner.os == 'Linux'
      run: |
        python -m venv ${{ matrix.venv-path }}
        source ${{ matrix.venv-path }}/bin/activate
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio
        pip install -r requirements.txt

    - name: Set up virtual environment on macOS
      if: runner.os == 'macOS'
      run: |
        python -m venv ${{ matrix.venv-path }}
        source ${{ matrix.venv-path }}/bin/activate
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio
        pip install -r requirements.txt

    - name: Set up virtual environment on Windows
      if: runner.os == 'Windows'
      run: |
        python -m venv ${{ matrix.venv-path }}
        .${{ matrix.venv-path }}\Scripts\Activate
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio
        pip install -r requirements.txt

    - name: Install HDF5 on macOS
      if: runner.os == 'macOS'
      run: brew install hdf5

    - name: Prepare requirements for macOS
      if: runner.os == 'macOS'
      run: |
        export HDF5_DIR=$(brew --prefix hdf5)
        grep -v '^mkl' requirements.txt > requirements_filtered.txt
        python -m pip install --upgrade pip
        pip install numpy scipy pytest pytest-asyncio
        pip install -r requirements_filtered.txt

    - name: Save dependencies in virtual environment on Ubuntu
      if: runner.os == 'Linux'
      run: |
        source ${{ matrix.venv-path }}/bin/activate
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio
        pip install -r requirements.txt

    - name: Save dependencies in virtual environment on macOS
      if: runner.os == 'macOS'
      run: |
        source ${{ matrix.venv-path }}/bin/activate
        grep -v '^mkl' requirements.txt > requirements_filtered.txt
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio
        pip install -r requirements_filtered.txt

    - name: Save dependencies in virtual environment on Windows
      if: runner.os == 'Windows'
      run: |
        .${{ matrix.venv-path }}\Scripts\Activate
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio
        pip install -r requirements.txt

    - name: Test with pytest on Ubuntu
      if: runner.os == 'Linux'
      run: |
        source ${{ matrix.venv-path }}/bin/activate
        pytest --log-level=DEBUG

    - name: Test with pytest on macOS
      if: runner.os == 'macOS'
      run: |
        source ${{ matrix.venv-path }}/bin/activate
        pytest --log-level=DEBUG

    - name: Test with pytest on Windows
      if: runner.os == 'Windows'
      run: |
        .${{ matrix.venv-path }}\Scripts\Activate
        pytest --log-level=DEBUG
