name: Reusable Test Workflow

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      venv-path:
        required: true
        type: string

jobs:
  setup-and-test:
    runs-on: ${{ inputs.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - uses: actions/cache@v3
      id: venv-cache
      with:
        path: ${{ inputs.venv-path }}
        key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-

    - name: Set up virtual environment on Ubuntu
      if: runner.os == 'Linux'
      run: |
        python -m venv ${{ inputs.venv-path }}
        source ${{ inputs.venv-path }}/bin/activate
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio
        pip install -r requirements.txt

    - name: Set up virtual environment on macOS
      if: runner.os == 'macOS'
      run: |
        python -m venv ${{ inputs.venv-path }}
        source ${{ inputs.venv-path }}/bin/activate
        brew install hdf5
        grep -v '^mkl' requirements.txt > requirements_filtered.txt
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio
        pip install -r requirements_filtered.txt

    - name: Set up virtual environment on Windows
      if: runner.os == 'Windows'
      run: |
        python -m venv ${{ inputs.venv-path }}
        .${{ inputs.venv-path }}\Scripts\Activate.ps1
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio
        pip install -r requirements.txt

    - name: Test with pytest on Ubuntu
      if: runner.os == 'Linux'
      run: |
        source ${{ inputs.venv-path }}/bin/activate
        pytest --log-level=DEBUG

    - name: Test with pytest on macOS
      if: runner.os == 'macOS'
      run: |
        source ${{ inputs.venv-path }}/bin/activate
        pytest --log-level=DEBUG

    - name: Test with pytest on Windows
      if: runner.os == 'Windows'
      run: |
        .${{ inputs.venv-path }}\Scripts\Activate.ps1
        pytest --log-level=DEBUG
