name: Run Tests

on: [workflow_call]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --user -r requirements.txt
        pip install --user pytest pytest-asyncio

    - name: Run pytest
      run: pytest --log-level=DEBUG
      env:
        PYTHON_LOG_LEVEL: DEBUG
