name: Run Tests

on: [workflow_call]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run pytest
      run: pytest --log-level=DEBUG
      env:
        PYTHON_LOG_LEVEL: DEBUG
