name: Setup Python

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  setup-python:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
