name: macOS [latest]

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    uses: ./.github/workflows/reusable-test.yml
    with:
      os: macos-latest
      venv-path: .venv
